pipeline {
    agent any
    stages {
        stage('Setup Test Framework') {
            steps {
                git poll: false, branch: 'cleanup', url: 'https://github.com/rancher/rancher2-scaling'
		dir("testing") {
			sh 'sudo apt-get install python3'
			sh 'curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py'
			sh 'python --version'
			sh 'pip --version'
			sh 'python3 get-pip.py'
			sh 'pip install --upgrade pip'
			sh 'ls'
			sh 'python3 run.py'
                        sh 'ls'
		}
            }
	}
    }
}
