pipeline {
    agent any
    environment {
        SOMETHING = ''
    }
    stages {
	stage('Cleanup') {
	    steps {
                // when Jenkins is updated, this should be replaced with WsCleanup()
		step(wsCleanup)
		// step([$class: 'WsCleanup'])
            }
	}
        stage('Setup Test Framework') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/rancher/rancher2-scaling'
            }
	}
	stage('Terraform') {
            steps {
		sh 'ls'
		sh 'pwd'
		// use dir("") {} instead
		sh 'cd control-plane'
		sh 'pwd'
                sh 'ls'
		sh 'curl https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip --output terraform.zip'
		sh 'ls'
		sh 'unzip terraform.zip'
		sh 'ls'
		sh 'mv terraform /usr/local/bin'
		sh 'terraform init'
            }
        }
    }
}
