pipeline {
    agent any
    environment {
        SOMETHING = ''
    }
    stages {
	stage('Cleanup') {
	    steps {
		deleteDir()
            }
	}
        stage('Setup Test Framework') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/rancher/rancher2-scaling'
		dir("testing") {
			sh 'sudo apt-get install python3'
			sh 'pip install pip3'
			sh 'pip install --upgrade setup-tools'
			sh 'pip install -r requirements.txt'
			sh 'python testbench.py'
		}
            }
	}
	/*
	stage('Terraform') {
            steps {
		// use dir("") {} instead
		dir("control-plane") {
			sh 'pwd'
			sh 'ls'
			sh 'curl https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip --output terraform.zip'
			sh 'ls'
			sh 'unzip terraform.zip'
			sh 'ls'
			sh 'mv terraform /usr/local/bin'
			sh 'terraform init'
			sh 'terraform apply -input=false -auto-approve'
			sh 'cat rancher.tfstate'
			// sh 'terraform destroy -input=false -auto-approve'
		}
            }
        } */
    }
}
